<a href="https://colab.research.google.com/github/Jwaminju/Algorithm_01/blob/main/Python_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%8B%9C%EA%B0%81%ED%99%94_Python_%EA%B3%A0%EA%B8%89_%EC%9E%90%EB%A3%8C%EA%B5%AC%EC%A1%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy
- 난수 생성
- 선형대수

In [ ]:
import numpy as np

random 난수 생성

In [ ]:
np.random.randint(6) # 0~5

1

In [ ]:
np.random.randint(1,20) # 1~19

16

In [ ]:
np.random.randint(1,20, size=10) # 여러 개_array

array([10,  7, 17, 18,  8,  8, 11,  8, 12,  8])

균일 분포

In [ ]:
np.random.rand(6) # 0~1 균일분포 6개_1차원 array

array([0.90933803, 0.85490017, 0.73149968, 0.19330077, 0.43661936,
       0.11017693])

In [ ]:
np.random.rand(3,2) # 2차원_array

array([[0.83718023, 0.19694461],
       [0.68942813, 0.03820633],
       [0.58814803, 0.45279886]])

평균0, 표준편차 1인 표준정규분포에서 랜덤 추출

In [ ]:
np.random.randn(6)

array([ 0.4359139 , -0.90909244, -1.32456139,  0.80932181, -0.41188233,
       -0.67158637])

In [ ]:
np.random.randn(3,2)

array([[-0.41048139,  1.30064973],
       [-0.1432949 ,  0.84155548],
       [-1.06798103,  0.7612203 ]])

Array 배열

In [ ]:
data1= [1,2,3,4,5]
data1

[1, 2, 3, 4, 5]

In [ ]:
arr1 = np.array(data1)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1.shape # array의 크기 및 형태

(5,)

In [ ]:
arr1.dtype # 데이터 유형 확인

dtype('int64')

In [ ]:
arr2 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2.shape

(3, 3)

numpy 연산은 크기가 서로 동일한 array끼리 연산이 진행된다.

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1.shape

(2, 3)

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr1 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [ ]:
arr1 - arr2

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr1 * arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [ ]:
arr1 / arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

array의 브로드캐스트: 크기가 다른 array끼리 연산이 가능하다

In [ ]:
arr2 = np.array([1,2,3])

In [ ]:
arr1 + arr2 # arr1에 arr2를 반복해서 더한다

array([[2, 4, 6],
       [5, 7, 9]])

In [ ]:
arr2 = np.array([1,2]) # 가장 최소한의 단위는 같아야하는 듯
arr1 + arr2

ValueError: ignored

In [ ]:
arr1 * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [ ]:
arr1 ** 2 # 제곱

array([[ 1,  4,  9],
       [16, 25, 36]])

Pandas
- 데이터 분석에 대표적
- 데이터 구조 수정, 조작에 용이
- 엑셀 로드

In [ ]:
 import pandas as pd

Series

In [ ]:
x = [1, -5, 7, 4, 8]
x

[1, -5, 7, 4, 8]

In [ ]:
pd.Series(x) # 마지막에 데이터타입이 나온다

0    1
1   -5
2    7
3    4
4    8
dtype: int64

In [ ]:
x = [1, 'z', 4.8]

In [ ]:
pd.Series(x)

0      1
1      z
2    4.8
dtype: object

Series는 데이터 타입이 한 가지만 들어갈 수 있어서, object 타입이 된다. 모두 object로 바뀜

In [ ]:
dt1 = pd.Series(x)
dt1

0      1
1      z
2    4.8
dtype: object

In [ ]:
dt1.values

array([1, 'z', 4.8], dtype=object)

In [ ]:
dt1.dtypes # 0은 object 즉, 말할 수 없는 데이터 타입이라는 것인가?

dtype('O')

In [ ]:
dt1 = pd.Series([1,2,3,4])
dt1

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
dt1.values # object 일때만 데이터 타입 출력하는가?

array([1, 2, 3, 4])

In [ ]:
dt1.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
dt1.dtypes # 데이터 유형 확인

dtype('int64')

인덱스 사전 정의

In [ ]:
dt2 = pd.Series([1,2,3,-4], index = ['a', 'b', 'c', 'd'])
dt2

a    1
b    2
c    3
d   -4
dtype: int64

In [ ]:
dt2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
dt1 = pd.Series(['a', 'b', 'c', 'd']) # 문자열이 object? 문자열이 따로 없는 건가???????????????????????????
dt1

0    a
1    b
2    c
3    d
dtype: object

리스트 뿐만 아니라 튜플, 딕셔너리로도 series를 만들 수 있다

In [ ]:
data = ('홍길동', '2000-06-17', '남', True) # 튜플
dt3 = pd.Series(data, index = ['이름', '생년월일', '성별', '수강여부'])
dt3

이름             홍길동
생년월일    2000-06-17
성별               남
수강여부          True
dtype: object

In [ ]:
data = {'d': 1, 'b': -5, 'e': 7, 'a': 4} # 키 값이 index로 활용이 됨
dt3 = pd.Series(data)
dt3

d    1
b   -5
e    7
a    4
dtype: int64

In [ ]:
dt3.name = 'series일므'

In [ ]:
dt3.index.name = 'index이름'

In [ ]:
dt3

index이름
d    1
b   -5
e    7
a    4
Name: series일므, dtype: int64

In [ ]:
dt3.index = ['Kim', 'Lee', 'Jwa', 'Oh'] # index.name도 초기화 됨
dt3

Kim    1
Lee   -5
Jwa    7
Oh     4
Name: series일므, dtype: int64

In [ ]:
dt3.index.name = '이름'

In [ ]:
dt3

이름
Kim    1
Lee   -5
Jwa    7
Oh     4
Name: series일므, dtype: int64

DataFrame

In [ ]:
df1 = pd.DataFrame([['a', 10, 100], ['b', 10, 100]]) # 열마다 다른 데이터 유형
df1

0   1    2
0  a  10  100
1  b  10  100

In [ ]:
df2 = pd.DataFrame([['a', 10, 100], ['b', 10, 100]], columns = ['v1', 'v2', 'v3'], index = ['x1', 'x2']) # 행이 index
df2

v1  v2   v3
x1  a  10  100
x2  b  10  100

리스트 타입 보다 딕셔너리 타입으로 많이 사용합니다

In [ ]:
df2 = pd.DataFrame(data = {'val0': ['a', 'b', 'c', 'd'], 'val1' : [1, 2, 3, 4]}, index = ['x1', 'x2']) # 키가 열이 됨
df2

ValueError: ignored

In [ ]:
df2 = pd.DataFrame(data = {'val0': ['a', 'b', 'c', 'd'], 'val1' : [1, 2, 3, 4]}, columns = ['val0', 'val1'], index = ['x1', 'x2', 'x3', 'x4']) 
# index만 넣으면 안됨. column도 같이 넣어줘야함.
#  그리고 한 키에 대한 value는 열이 된다
df2

val0  val1
x1    a     1
x2    b     2
x3    c     3
x4    d     4

In [ ]:
df2 = pd.DataFrame(data = {'val0': ['a', 'b', 'c', 'd'], 'val1' : [1, 2, 3, 4]}, columns = ['v0', 'v1'], index = ['x1', 'x2', 'x3', 'x4']) 
# 딕셔너리에서 전달인자 column은 데이터의 동일한 key값을 가져야한다.

v0   v1
x1  NaN  NaN
x2  NaN  NaN
x3  NaN  NaN
x4  NaN  NaN

In [ ]:
df2 = pd.DataFrame(data = {'val0': ['a', 'b', 'c', 'd'], 'val1' : [1, 2, 3, 4]}, columns = data.keys, index = ['x1', 'x2']) 
# 꼼수도 안됨
df2

TypeError: ignored

In [ ]:
data = {'val0': ['a', 'b', 'c', 'd'], 'val1' : [1, 2, 3, 4]}
df2 = pd.DataFrame(data, columns = data.keys, index = ['x1', 'x2', 'x3', 'x4']) 
# 꼼수도 안됨
df2

TypeError: ignored

In [ ]:
df2.index.name = 'No'
df2.columns.name = 'info'
df2

info   v1   v2
No            
x1    NaN  NaN
x2    NaN  NaN

In [ ]:
data = {'val0': ['a', 'b', 'c', 'd'], 'val1' : [1, 2, 3, 4]}
df2 = pd.DataFrame(data) 
df2

val0  val1
0    a     1
1    b     2
2    c     3
3    d     4

In [ ]:
 df2.index = ['x1', 'x2'] # 데이터의 개수가 맞아야한다

ValueError: ignored

In [ ]:
 df2.index = ['x1', 'x2', 'x3', 'x4'] # 이런 꼼수가 안 통할 때 column과 키값이 어처피 중복되니, 귀찮다면 index만 넣는 방법이다 

In [ ]:
df2

val0  val1
x1    a     1
x2    b     2
x3    c     3
x4    d     4

복습 문제

In [ ]:
A = np.array([2, 3, 4, 5, 6, 7])
B = np.array([1,1,3,3,5,5])
A = A.reshape(3,2)
B = B.reshape(3,2)
print(A, '',B)

[[2 3]
 [4 5]
 [6 7]]  [[1 1]
 [3 3]
 [5 5]]


딕셔너리 방식으로 데이터프레임을 생성하라.

In [ ]:
df = pd.DataFrame(data = {'학번': [201901, 201902, 202001, 201504, 201402, 201809], 
                          '이름':['원빈', '우빈', '강준', '나라', '사랑', '최준'],
                          '성적': [70, 90, 80, 100, 75, 79],
                          '학점': ['C', 'A', 'B', 'A+', 'C+', 'C+']})
df

학번  이름   성적  학점
0  201901  원빈   70   C
1  201902  우빈   90   A
2  202001  강준   80   B
3  201504  나라  100  A+
4  201402  사랑   75  C+
5  201809  최준   79  C+

In [ ]:
df.index = ['a', 'b', 'c', 'd', 'e', 'f']
df

학번  이름   성적  학점
a  201901  원빈   70   C
b  201902  우빈   90   A
c  202001  강준   80   B
d  201504  나라  100  A+
e  201402  사랑   75  C+
f  201809  최준   79  C+